title: Headers
modelClass: Dizoo\PageHeaders\Models\Headers
list: $/dizoo/pageheaders/models/headers/columns.yaml
recordUrl: 'dizoo/pageheaders/headers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: pageid
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
